package com.example.demo.proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video_info.proto
// Protobuf Java Version: 4.29.1

public final class VideoInfo {
  private VideoInfo() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      VideoInfo.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VideoFeatureOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VideoFeature)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 author_gender = 1;</code>
     * @return Whether the authorGender field is set.
     */
    boolean hasAuthorGender();
    /**
     * <code>optional int32 author_gender = 1;</code>
     * @return The authorGender.
     */
    int getAuthorGender();

    /**
     * <code>optional int64 channel_id = 2;</code>
     * @return Whether the channelId field is set.
     */
    boolean hasChannelId();
    /**
     * <code>optional int64 channel_id = 2;</code>
     * @return The channelId.
     */
    long getChannelId();

    /**
     * <code>optional string author_name = 3;</code>
     * @return Whether the authorName field is set.
     */
    boolean hasAuthorName();
    /**
     * <code>optional string author_name = 3;</code>
     * @return The authorName.
     */
    String getAuthorName();
    /**
     * <code>optional string author_name = 3;</code>
     * @return The bytes for authorName.
     */
    com.google.protobuf.ByteString
        getAuthorNameBytes();
  }
  /**
   * Protobuf type {@code VideoFeature}
   */
  public static final class VideoFeature extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:VideoFeature)
      VideoFeatureOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 1,
        /* suffix= */ "",
        VideoFeature.class.getName());
    }
    // Use VideoFeature.newBuilder() to construct.
    private VideoFeature(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private VideoFeature() {
      authorName_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return VideoInfo.internal_static_VideoFeature_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return VideoInfo.internal_static_VideoFeature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              VideoFeature.class, Builder.class);
    }

    private int bitField0_;
    public static final int AUTHOR_GENDER_FIELD_NUMBER = 1;
    private int authorGender_ = 0;
    /**
     * <code>optional int32 author_gender = 1;</code>
     * @return Whether the authorGender field is set.
     */
    @Override
    public boolean hasAuthorGender() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 author_gender = 1;</code>
     * @return The authorGender.
     */
    @Override
    public int getAuthorGender() {
      return authorGender_;
    }

    public static final int CHANNEL_ID_FIELD_NUMBER = 2;
    private long channelId_ = 0L;
    /**
     * <code>optional int64 channel_id = 2;</code>
     * @return Whether the channelId field is set.
     */
    @Override
    public boolean hasChannelId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int64 channel_id = 2;</code>
     * @return The channelId.
     */
    @Override
    public long getChannelId() {
      return channelId_;
    }

    public static final int AUTHOR_NAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile Object authorName_ = "";
    /**
     * <code>optional string author_name = 3;</code>
     * @return Whether the authorName field is set.
     */
    @Override
    public boolean hasAuthorName() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string author_name = 3;</code>
     * @return The authorName.
     */
    @Override
    public String getAuthorName() {
      Object ref = authorName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        authorName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string author_name = 3;</code>
     * @return The bytes for authorName.
     */
    @Override
    public com.google.protobuf.ByteString
        getAuthorNameBytes() {
      Object ref = authorName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        authorName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, authorGender_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, channelId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, authorName_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, authorGender_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, channelId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, authorName_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof VideoFeature)) {
        return super.equals(obj);
      }
      VideoFeature other = (VideoFeature) obj;

      if (hasAuthorGender() != other.hasAuthorGender()) return false;
      if (hasAuthorGender()) {
        if (getAuthorGender()
            != other.getAuthorGender()) return false;
      }
      if (hasChannelId() != other.hasChannelId()) return false;
      if (hasChannelId()) {
        if (getChannelId()
            != other.getChannelId()) return false;
      }
      if (hasAuthorName() != other.hasAuthorName()) return false;
      if (hasAuthorName()) {
        if (!getAuthorName()
            .equals(other.getAuthorName())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAuthorGender()) {
        hash = (37 * hash) + AUTHOR_GENDER_FIELD_NUMBER;
        hash = (53 * hash) + getAuthorGender();
      }
      if (hasChannelId()) {
        hash = (37 * hash) + CHANNEL_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getChannelId());
      }
      if (hasAuthorName()) {
        hash = (37 * hash) + AUTHOR_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getAuthorName().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static VideoFeature parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VideoFeature parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VideoFeature parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VideoFeature parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VideoFeature parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VideoFeature parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VideoFeature parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static VideoFeature parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static VideoFeature parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static VideoFeature parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static VideoFeature parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static VideoFeature parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(VideoFeature prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VideoFeature}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VideoFeature)
        VideoFeatureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return VideoInfo.internal_static_VideoFeature_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return VideoInfo.internal_static_VideoFeature_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                VideoFeature.class, Builder.class);
      }

      // Construct using VideoInfo.VideoFeature.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        authorGender_ = 0;
        channelId_ = 0L;
        authorName_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return VideoInfo.internal_static_VideoFeature_descriptor;
      }

      @Override
      public VideoFeature getDefaultInstanceForType() {
        return VideoFeature.getDefaultInstance();
      }

      @Override
      public VideoFeature build() {
        VideoFeature result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public VideoFeature buildPartial() {
        VideoFeature result = new VideoFeature(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(VideoFeature result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.authorGender_ = authorGender_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.channelId_ = channelId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.authorName_ = authorName_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof VideoFeature) {
          return mergeFrom((VideoFeature)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(VideoFeature other) {
        if (other == VideoFeature.getDefaultInstance()) return this;
        if (other.hasAuthorGender()) {
          setAuthorGender(other.getAuthorGender());
        }
        if (other.hasChannelId()) {
          setChannelId(other.getChannelId());
        }
        if (other.hasAuthorName()) {
          authorName_ = other.authorName_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                authorGender_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                channelId_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                authorName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int authorGender_ ;
      /**
       * <code>optional int32 author_gender = 1;</code>
       * @return Whether the authorGender field is set.
       */
      @Override
      public boolean hasAuthorGender() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 author_gender = 1;</code>
       * @return The authorGender.
       */
      @Override
      public int getAuthorGender() {
        return authorGender_;
      }
      /**
       * <code>optional int32 author_gender = 1;</code>
       * @param value The authorGender to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorGender(int value) {

        authorGender_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 author_gender = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthorGender() {
        bitField0_ = (bitField0_ & ~0x00000001);
        authorGender_ = 0;
        onChanged();
        return this;
      }

      private long channelId_ ;
      /**
       * <code>optional int64 channel_id = 2;</code>
       * @return Whether the channelId field is set.
       */
      @Override
      public boolean hasChannelId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int64 channel_id = 2;</code>
       * @return The channelId.
       */
      @Override
      public long getChannelId() {
        return channelId_;
      }
      /**
       * <code>optional int64 channel_id = 2;</code>
       * @param value The channelId to set.
       * @return This builder for chaining.
       */
      public Builder setChannelId(long value) {

        channelId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 channel_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannelId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        channelId_ = 0L;
        onChanged();
        return this;
      }

      private Object authorName_ = "";
      /**
       * <code>optional string author_name = 3;</code>
       * @return Whether the authorName field is set.
       */
      public boolean hasAuthorName() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string author_name = 3;</code>
       * @return The authorName.
       */
      public String getAuthorName() {
        Object ref = authorName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          authorName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string author_name = 3;</code>
       * @return The bytes for authorName.
       */
      public com.google.protobuf.ByteString
          getAuthorNameBytes() {
        Object ref = authorName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          authorName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string author_name = 3;</code>
       * @param value The authorName to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorName(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        authorName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string author_name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthorName() {
        authorName_ = getDefaultInstance().getAuthorName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string author_name = 3;</code>
       * @param value The bytes for authorName to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        authorName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:VideoFeature)
    }

    // @@protoc_insertion_point(class_scope:VideoFeature)
    private static final VideoFeature DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new VideoFeature();
    }

    public static VideoFeature getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VideoFeature>
        PARSER = new com.google.protobuf.AbstractParser<VideoFeature>() {
      @Override
      public VideoFeature parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<VideoFeature> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<VideoFeature> getParserForType() {
      return PARSER;
    }

    @Override
    public VideoFeature getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VideoFeature_descriptor;
  private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VideoFeature_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020video_info.proto\"\216\001\n\014VideoFeature\022\032\n\ra" +
      "uthor_gender\030\001 \001(\005H\000\210\001\001\022\027\n\nchannel_id\030\002 " +
      "\001(\003H\001\210\001\001\022\030\n\013author_name\030\003 \001(\tH\002\210\001\001B\020\n\016_a" +
      "uthor_genderB\r\n\013_channel_idB\016\n\014_author_n" +
      "ameb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_VideoFeature_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VideoFeature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_VideoFeature_descriptor,
        new String[] { "AuthorGender", "ChannelId", "AuthorName", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
